services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro

  application-server:
    image: alexwhen/docker-2048
    expose:
      - 80

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - eyJhIjoiMGFiNGRhNTUxZGQ5NTM3YzJhMDBkNWI1Y2M2NzY5YzEiLCJ0IjoiOWJlZjMxOTAtZTEzYy00ZTdkLWJmYWUtMGYwMmY4MzE4OTkxIiwicyI6Ill6RTFNREExWlRrdFlXWmtNUzAwTkdJNUxUbGtOV1l0WkRWaU56VTNaVGc0TldabSJ9