entryPoints:
  web:
    address: ":80"

serversTransport:
  insecureSkipVerify: true

providers:
  docker: {}

api:
  dashboard: true

log:
  level: INFO

accessLog: {}

# noinspection YAMLSchemaValidation
http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:test!123"
  routers:
    traefik:
      rule: "Host(`junwork.net`) && PathPrefix(`/traefik`)"
      service: "api@internal"
      entry Points:
        - web

    myapp:
      rule: "Host(`labs.wisenut.kr`)"
      service: "myapp"
      entryPoints:
        - web

  services:
    myapp:
      loadBalancer:
        servers:
          - url: "http://application-server:80"
