kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  disableDefaultCNI: false
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings: # 외부에서 접속할 수 있도록 포트 매핑
      # Container Port와 Node Port가 같아야 한다.
      - containerPort: 80 # Ingress Controller가 사용하는 포트
        hostPort: 80
        protocol: TCP
      - containerPort: 443 # Ingress Controller가 사용하는 포트
        hostPort: 443
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker